### ISSUE TITLE
How to configure attachment from filestore >> Alfresco

### ISSUE THREAD

**Issue by vincentlaurent** [acsone/alfodoo#117]
Hello Laurent

Can you explain how to change the by default behaviour of Odoo when printing qweb. The pdf generated is attached in the filestore and I would rather see it transferd to Alfresco

Thanks and happy new year

**Comment by lmignon** [comment]
Helle @vincentlaurent 

Alfodoo doesn't provide this kind of functionality by default. We developed some specialized addons to implement this functionality on top of a patched Odoo 10. https://github.com/acsone/alfodoo/tree/10.0-cmis_report_write-jne
The entry point of these addons is the method ` _postprocess_report` https://github.com/acsone/alfodoo/blob/10.0-cmis_report_write-jne/cmis_report_write/models/report.py#L32 (this method is an override of a method called at the end of the report generation process into our patched Odoo https://github.com/acsone/odoo/commit/33666ca8cce6dadca226a961a8bdf2f84e159c43)
The code could be easily ported in 12.0 and should no more require to patch odoo since the `post process` hook is now part of the api https://github.com/acsone/odoo/blob/12.0/odoo/addons/base/models/ir_actions_report.py#L162)

Regards
