### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by sumankhk** [acsone/alfodoo#91]
Can anybody help me with this error?Its urgent
@zakiuu @lmignon @sbidoul @Cedric-Pigeon 

![jserror](https://user-images.githubusercontent.com/23263034/32938865-ba9d4580-cba5-11e7-8a86-5b9baa3a2d64.png)

**Comment by lmignon** [comment]
@sumankhk Why do you have closed #86 to reopen a new issue on the same topic? As said in #86 you should take a look into the browser console for a more meaningful error message.  (ctrl + shift + j) Without this information it's impossible to figure out what's working wrong. This module works perfectly with many of our customers. That's why I suspect a problem in your configurations. I would also like to remind you that we provide this module free of charge and that we have our own constraints. Therefore, we do our best to ensure a minimum of support according to our availability and this free of charge.

Regards,

lmi

**Comment by sumankhk** [comment]
@lmignon This module is working fine  locally in my system too...but i get this error during deployment..Sorry about that previous issue...i closed it after not getting any response from your team.

This is the error in my console:...Can u help?
![late js](https://user-images.githubusercontent.com/23263034/32941663-98a1076a-cbae-11e7-93ab-39ffe3b8365e.png)

**Comment by lmignon** [comment]
@sumankhk as you can see your browser is not able to connect to 192.168.2.7 on port 8080. It seems that you've configured an internal address for your alfresco server in place of a publicly available one.

**Comment by sumankhk** [comment]
Where exactly should we use the public IP....in the cmis Backend or the CORS allowed origins section?

**Comment by lmignon** [comment]
everywhere.

**Comment by lmignon** [comment]
This problem is a configuration problem.
